version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: prefect-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prefect_password
      POSTGRES_DB: prefect
    volumes:
      - prefectdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prefect-server:
    image: python:3.10-slim
    container_name: prefect-server
    depends_on:
      - postgres
    volumes:
      # Mount your local Prefect source if needed; otherwise remove/adjust
      - ../prefect/src:/app
    working_dir: /app
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:prefect_password@postgres:5432/prefect
      OTEL_SERVICE_NAME: prefect-server
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317   # Adjust to your collector host
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_LOG_LEVEL: debug
      PYTHONPATH: /app
    command: >
      /bin/bash -c "
        pip install --no-cache-dir opentelemetry-instrument uvicorn prefect
        opentelemetry-instrument
          uvicorn
          --factory prefect.server.api.server:create_app
          --host 0.0.0.0
          --port 4200
          --timeout-keep-alive 5
      "
    ports:
      - "4200:4200"

  prefect-worker:
    image: python:3.10-slim
    container_name: prefect-worker
    depends_on:
      - prefect-server
    volumes:
      - ../prefect/src:/app
    working_dir: /app
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:prefect_password@postgres:5432/prefect
      PYTHONPATH: /app
    command: >
      /bin/bash -c "
        pip install --no-cache-dir prefect
        prefect --no-prompt work-pool create local --type process --overwrite &&
        prefect --no-prompt deploy --all --prefect-file load_testing/prefect.yaml &&
        prefect worker start -p local
      "

volumes:
  prefectdb:
